### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by startupgurukul** [otcshare/chromium-src#115]
Hi folks, this is just a request and asking it is too much after the contribution to webnn itself

this is a very active repo and building one everytime is resource intensive for an average programmer, it would be awesome if you can setup something like this for webml branch.  

https://download-chromium.appspot.com/

**Comment by ibelem** [comment]
@startupgurukul Many thanks for your attention in the WebNN project. Your idea is reasonable which is more convenience for others, but due to the legal and some process issues, currently the nightly builder is only for internal usage only, please still to build the repo by yourself.

**Comment by ibelem** [comment]
I will close this issue and thanks again! :)

**Comment by startupgurukul** [comment]
Understood, thanks for trying.

Once again great effort and looking forward to a new world where DL is a part of everyone's life via webnn.
